# Plugins
gems:
- jekyll-sitemap
safe: true

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "SwanseaCon 2016 - Agile Development & Software Craftsmanship conference"
email: "hello@swanseacon.co.uk"
description: "SwanseaCon is an agile development & software craftsmanship conference"
baseurl: ""
url: "http://swanseacon.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-57225674-1"
googleAnalyticsSiteUrl: "swanseacon.co.uk"
# siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "SwanseaCon"
organizerAlternateName: "Viv Richards"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "contact@vivrichards.co.uk"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.vivrichards.co.uk/"

# Head
metaKeywords: "event, swansea, conference, swanseacon, programming, development, software, developers, south wales, craftsmanship, agile"
twitterAccount: "@SwanseaCon"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/SwanseaCon_2015_Sponsorship.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/sponsors/", text: "Sponsors"}
 - {permalink: "/logistics/", text: "Logistics"}
bottomNavigationLinks:
rightNavigationButtons:
 - {link: "#about", text: "About SwanseaCon"}


# Hero Block
heroImage: "hero.jpg"
heroTitle: "2nd Agile Development & Software Craftsmanship <typeout>conference"
eventDate: "Monday 12th September - Tuesday 13th September, 2016"
typeoutTextValues: '"", "Agile", "Development", "Software", "Craftsmanship"'
typeoutFallback: ""
heroButtons:
 - {permalink: "#about", text: "About SwanseaCon"}

# About Block
aboutTitle: "About SwanseaCon<p><strong><em>Profits made from SwanseaCon 2015 have gone toward helping provide free netbooks for children, which they will use to learn to code at our free summer code camp.</em></strong></p>"
aboutBlock:
 - {title: " 	", image: "code.jpg", text: "<br><br><p>SwanseaCon is a technical event for Software Developers, Software Architects, Project Managers, Analysts and Consultants in Wales. The second year is scheduled to kick start on 12th of September and go on until the 13th of September 2016 at the Liberty Stadium, Swansea, South Wales.</p>
 <p>SwanseaCon 2016 will be our second agile development and software craftsmanship conference in Swansea, South Wales. Exploring the latest agile and lean thinking in software craftsmanship, teams and business. The conference hopes to attract people from all parts of the globe to explore, evolve and find out what it means to be truly agile in business, from its culture to product development practices.</p>
 <p>SwanseaCon 2016 gives you and your colleagues the right platform to gather cutting-edge information on technology from the best speakers and trainers of the industry. </p>
 <p>The conference includes keynotes and presentations, a discussion panel, an opening reception, and time between sessions to network and connect with colleagues from around the world.</p>
 <p>Delegates will get the opportunity to learn how to increase their productivity dramatically and save cost, learn how to enhance the quality of their software applications, as well as meet their peers in a productive and social environment.</p>" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "150", specialCharacter: "+", info: "attendees", detail: ""}
 - {count: "18", specialCharacter: "+", info: "hours", detail: "of agile development & software craftsmanship"}
 - {count: "25", specialCharacter: "+", info: "speakers", detail: "from all around the world"}
 - {count: "2", specialCharacter: "", info: "parallel tracks", detail: "plus discussion panel"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "SwanseaCon 2015 Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers form 2015"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Liberty Stadium"
eventLocationLink: "http://www.liberty-stadium.com/"
eventStreetAddress: "Landore"
eventAddressLocality: "Swansea"
eventAddressLocalityRegion: ""
eventPostalCode: "SA1 2FA"
eventAddressCountry: "Wales"
eventStartTime: "2015-09-07T08:30"
eventDoorTime: "09:00"
eventEndTime: "2015-09-09T17:00"
eventPlaceCoordinates: "51.642697, -3.935307"
mapCenterCoordinates: "51.643472, -3.935207"
mapMobileCenterCoordinates: "51.643472, -3.935080"

# Venue Block
venueBlockTitle: "SwanseaCon"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Liberty Stadium"
venueFeatures: ["The premier venue for conference and events in South West Wales.", "Located in the heart of Swansea."]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "SwanseaCon"
twitterFeed: "_includes/twitter-feed.html"

# Partners Block
organizersTitle: ""
partnersTitle: "Sponsors for 2015"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates for 2016"
subscribeAction: "http://swancon.us10.list-manage.com/subscribe/post?u=6f529863589ed3eabebff1faf&amp;id=ac260fb163"
subscribeInfo: "Registration is now open. Number of tickets are limited."

# Tickets Block
ticketsTitle: "Tickets"
ticketTermsTitle: "Terms & Conditions"
ticketTermsInfo: "Please note that once booked, Conference and Workshop tickets cannot be cancelled and are non refundable. However, a substitute may be enrolled in a delegate’s place provided we are notified in writing before the first day of the event. Also note it is one ticket per delegate (ie no sharing). While SwanseaCon 2015 strives to maintain an up to date schedule, session list, and speaker list, these may be subject to change. If SwanseaCon has to cancel the conference for any reason, then we will refund 100% of any prepaid conference ticket fee, but we will not be liable for any other costs incurred including (for example) travel charges or any consequential damages, even if we were advised of them."
ticketsInfo: "Tickets grant access to all conference sections, coffee breaks, lunch and evening reception. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Book by 31st March"
  price: "350"
  priceCurrency: "GBP"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "https://www.picatic.com/swanseacon"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2015-02-15T10:00"
  validThrough: "2015-03-31T23:59"
 -
  name: "Book by 31st May"
  price: "450"
  priceCurrency: "GBP"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "https://www.picatic.com/swanseacon"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2015-04-01T00:00"
  validThrough: "2015-05-31T23:59"
  #disabled: false
 -
  name: "Standard Ticket"
  price: "200"
  priceCurrency: "GBP"
  ticketsNumber: "50"
  buyButtonLink: "https://www.picatic.com/swanseacon"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2015-06-01T10:00"
  validThrough: "2015-09-07T23:59"
  #soldOut: true
  #soldOutText: "Sold Out"
  #disabled: false
# Footer
socialLinks:
 - {link: "https://plus.google.com/u/1/105624973822199981487", icon: "google-plus"}
 - {link: "https://twitter.com/SwanseaCon", icon: "twitter"}
 - {link: "https://www.facebook.com/swanseacon", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.picatic.com/swanseacon", text: "picatic.com/swanseacon"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:hello@swanseacon.co.uk", text: "hello@swanseacon.co.uk"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "swanseacon2015"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "51.642697, -3.935307"
logisticsMapMobileCenterCoordinates: "51.642697, -3.935307"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Swansea"
directionDetailsCards:
 - {title: "Nearest airport", information: '<p>The nearest international airport is Cardiff International Airport - ring 01446 711111 or visit <a href="http://www.cardiff-airport.com/" target="_blank">Cardiff airport</a>.</p><p>Swansea has its own airport, which is suitable for small aircraft - please ring 01792 204063 or visit <a href="http://www.swanseaairport.com/" target="_blank">Swansea airport</a>.</p>'}
 - {title: "Coach and bus information", information: '<p>Greyhound operates a frequent shuttle coach service from Cardiff to Swansea and Bristol airport.  The service runs hourly off-peak and half-hourly at peak times.  There are frequent National Express coaches to Swansea too, from all other principal towns in south and west Wales. The National Express also links with London and Heathrow and Gatwick airports.</p><p>For bus routes in and around Swansea, contact Traveline Cymru on 0871 200 22 33 or visit the <a href="http://www.traveline-cymru.info/" target="_blank">Traveline Cymru website</a>.</p><p>National Express Coaches - 08705 808080 or <a href="http://www.nationalexpress.com/home.aspx" target="_blank">National Express</a>.</br>
Greyhound - <a href="http://www.greyhounduk.com/" target="_blank">Greyhound website</a></p>'}
 - {title: "Accommodation in Swansea", information: 'If you are planning to visit the area then the <a href="http://www.visitswanseabay.com/" target="_blank">Visit Swansea Bay</a> website has all you need to make the most of your stay.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels in Swansea"
    links:
     - {link: "http://www.mercureswansea.co.uk/", text: "Mercure Swansea"}
     - {link: "https://www.village-hotels.co.uk/hotels/swansea/", text: "Village"}
     - {link: "http://www.dragon-hotel.co.uk/", text: "The Dragon Hotel"}
     - {link: "http://www.premierinn.com/en/hotels/swansea/", text: "Premier Inn"}
     - {link: "http://www.tripadvisor.co.uk/Hotels-g186466-Swansea_Swansea_County_Southern_Wales_Wales-Hotels.html", text: "Trip Advisor"}
   -
    title: "Travelling to Swansea"
    links:
     - {link: "http://www.nationalrail.co.uk/stations_destinations/SWA.aspx", text: "National Rail"}
     - {link: "http://www.nationalexpress.com/waystosave/cheapcoachtickets.aspx", text: "National Express"}
     - {link: "http://www.greyhounduk.com/", text: "Greyhound"}
     - {link: "http://www.cardiff-airport.com/", text: "Cardiff Airport"}
     - {link: "http://www.swanseaairport.com/", text: "Swansea Airport"}
     - {link: "http://www.traveline-cymru.info/", text: "Traveline Cymru"}
     - {link: "http://www.swansea.gov.uk/traveltoswansea", text: "Travel to Swansea"}
   -
    title: "Places to visit in Swansea"
    links:
     - {link: "http://www.visitswanseabay.com/", text: "Visit Swansea Bay"}
     - {link: "http://www.dylanthomastheatre.org.uk/", text: "Dylan Thomas Theatre"}
     - {link: "http://www.swansea.gov.uk/oystermouthcastle", text: "Oystermouth Castle"}
     - {link: "http://www.mumbles-pier.co.uk/", text: "Mumbles Pier"}
     - {link: "http://www.tripadvisor.co.uk/Attractions-g186466-Activities-Swansea_Swansea_County_Southern_Wales_Wales.html", text: "Trip Advisor"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
